# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
# development:
#   adapter: mysql2
#   encoding: utf8
#   database: moogle
#   pool: 5
#   username: root
#   password:
#   socket: /tmp/mysql.sock
#   encoding: utf8
#   collation: utf8_general_ci

# RUN THIS COMMAND BEFORE USING DEVELOPMENT DB
# ssh -f deploy@ec2-50-17-115-76.compute-1.amazonaws.com -L 10008:127.0.0.1:3306 -N
# mysql -h127.0.0.1 -P10008 -udeploy -pgTSjMxHynG

# development:
#   adapter:   mysql2
#   database:  ohsnap
#   username:  deploy
#   password:  gTSjMxHynG
#   host: 127.0.0.1
#   port: 10008
  
development:
  adapter:   mysql2
  database:  ohsnap
  username:  friendmash
  password:  Lik3aG6
  host: friendmash-production.clhyg7sm4xmb.us-east-1.rds.amazonaws.com
  port: 3306

# development:
#     adapter:   mysql2
#     database:  ohsnap
#     username:  root 
#     password:  
#     host: localhost
#     port: 3306


# Engine Yard
# ec2-50-17-115-76.compute-1.amazonaws.com
# username: deploy
# password: gTSjMxHynG
    
# development:
#   adapter: sqlite3
#   database: db/development.sqlite3
#   pool: 5
#   timeout: 5000

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
