development:
  bucket: petmash
  access_key_id: AKIAJRFSK3RWQ7XLGNFA
  secret_access_key: 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

test:
  bucket: petmash
  access_key_id: AKIAJRFSK3RWQ7XLGNFA
  secret_access_key: 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

production:
  bucket: petmash
  access_key_id: AKIAJRFSK3RWQ7XLGNFA
  secret_access_key: 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
  
staging:
  bucket: petmash
  access_key_id: AKIAJRFSK3RWQ7XLGNFA
  secret_access_key: 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
  
